apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azuredns-config
  namespace: cert-manager
spec:
  encryptedData:
    client-secret: AgAPHM/NXWQv7FH9YY94UZuCcqUGMV7SJpuRbVlPZISa/dvM0NEqlLjooFa4pLFPVNhiplebNqymo1YRsUCuLxPxQyuJ9SnvSKUdhCW4RQK/6N1qLS++JDaJdPwFFOwTK7j6Jrbmx4zLM5NiIHJu6G1VZg4GbXGtmP3M01Ab1OnFAtAmb2JDtGFiQteY/YFYB+FUfrQdwIMsu5Ti1Q3gnqRIrf56vReW4E4dUmi+QZxmvNh0FQ3zcH7ubf3PIlBtToS9OD9tpBGOoHgHcHNxO1grQ51RpHi3ZEzkxWJnnCJWTttc/gt8r7rhKE0fHNkBBWIhBqoBu3hno/uKDSjgYIw6q6AcL+w8PaQE3BlJaEeb9h3VU5+9+qI68oZO5bsw3fCDzskVLiCMMtze8wocGI1b9slrFLDUHD0R5uLL2Op2dNYhdbVzxmcyKuwUZuc9di3PB62UpXhxH7jRnNf3DQBwQk2xPt5s9EF6Zjlvv6sx8bwgek0+CuN2MWAGQcXXYlyI3ZWl+/+5lqAcAoMjCLsZpXSvnDfqFcXYxFnyFtARHDPT9NgpJYFSBZRtBdAX1IUTRgaTzPlo7yg669GYm5Ff0vZ9yHzicw8uYRhzbFz/T6ahEbSIJ4AsPWJLb6CkFGKNAEnh6CU7kEOZtc1NYkRrLPDE2cMsSPqUhd3DYbf8uR4OYMyKZpXmFjAP+FbpC+xioPU84iBojU5JRC5kKiGkoTX3tyh9hLE63tbW6ZKS5XZjPxc=
  template:
    metadata:
      creationTimestamp: null
      name: azuredns-config
      namespace: cert-manager
status: {}

