apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azuredns-config
  namespace: cert-manager
spec:
  encryptedData:
    client-secret: AgCHFF5cL5Yy2e3pNHncu/zykq+VcRI02isfneugcY9nnzgGUD14vKJR/uX7vFZ6LTAxcPW3hxqbBQTVYT7p8qvCBXfZhbKWnzzkRJiLsjXdPHPqvgW6OvNZFdSqaCIGPaye5IpoBDzUoDrbk4PYk2kgKpYSZOppueSJeZQ1ARRE/+WbzjOIvnG8HA0chsQU7R+Cid84C4FTbWQq8mJW0meAivNe7XVbe24+18NjMVgCSU/jm5z8xxr5baBviYAEJ08XqwsFr2AOsJCWS6l3D+t1fmogdQA/xiRAkJIY5bSfJHX/6Zglkm9eW1RKGitlOnVsCIj1oMNR0+rnXF+5wysDA85Ayi3nXsAAQkqyJPX0X6g8ceaobfSaDPw4t+zbw1s21/9mkx6qlc7X1V8caXEeCtKSrGM2a/VyecVaSS8rfRYhovU+H1IQt2GdOSlZCC3z0zfryqzgCCfBAvb4R/pbVW1W18z1DtucRAnEkRh4GiN2rvMhI9Qo6QucqVLGhhxdJKxqqLXgtadVx7BG5kzYPHd/j5SYI4nNutu6DKbt3gXLWddpb60JUxlAVF4Npe851a3wIIfUKP3rmX63u7a2Wxeex9xmHQWu/x1GlKOyiWWVDka7nDMa22IY6FLrr8pCLdy90EFnfuFp5D+PjJhowCA0ivp8VONVKt/Fatj1w8iNOYaAWAQv3m/11mWFyjF/jBKu4GceBxnKuhpj+x+GPxXfcFkDESoz/9/57SMBmQOZxP4=
  template:
    metadata:
      creationTimestamp: null
      name: azuredns-config
      namespace: cert-manager
status: {}

