apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAsvkE0ichclaa/5gU9ZWZX7cU1feK4ZhE7u1m7HKbZyfk8rOXJUwPP2jmmCgJ7WL9UzHjfS/TX20I/l+13CvPT+LakwGZ7AFAk6dfYCcy+fTn5DgC2bD/UYYVaXCGOq6HqHX0ElD+1mMEgxexJamxoR9KXK8wqU8gRsszsPMJWtCvx3RjTXq5gk1juKQOU+d/3U96t0KUwisXosBE/kXjZqtG0jw/kvKXEjUYcXlMeXGycr9eXgO86P5j5gTfnMSYy9rpZVvIqRNimNO9R9m9vr/YiRLghXFM37TSVYNd0Jj2qXvxkI9JJvsoRXU/RzSr10kMJbPXUEGBDl0Wktp7bQ3bgnLro5pmLoWh1oOEC32pfVZZQj+2hor7LNzEBElhXcjAZfy2raWuKl+8iwFCiP9Bn1Cky8tXrvFCXOmyEglZCcqkQ3fTfk9cir/gtbrc+FB1i8k/+p2Rb0oWqT5ec02RcolQZr15u1jolzjCoHZ1oDoKIzRMsxQnMj24u2LEh3rhZUrhOy4SbhVe+SfF+8f3/yuin8TE40kgSc0BAFKxFRD0USdrpt1pFE0NPFPmDjPi1dvrrWOtDewxGjwJ2seaLNNdhP4r/wSiPq1MxFwaLtsjnRnJSXA3k0IKHKbpkmJdiEMvORO/QvsphQQpZdQWkm5d9MdlFmAEhEZ2CJKLoVHufR3IMJFWXyA/h9pxBGbp6qK4k2kEv5KJyqr6DBndSp9eh+zEYIneqyxvDo4syLtY0KbVJiSr0ODmluErtmSJTvpLsFX3n/JHW7dzbnJrGUEsqX2aB+U2aDFLTB8vrFMw7VGFZ
  template:
    metadata:
      creationTimestamp: null
      name: nzbget-helm-values
      namespace: default
status: {}

