apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCmiw/8WEyki0Sx3qcln7gGpAjvox55cqUVD87n9pk/Y1OFy93BLz6Vtqrh+OKYqdH+hXk1nYdfFT4mbOpqg1OfzmjTuu+2aaAK6pNRJ7Nps6d8mKuSm0O1cLKW+6DU4y6HBJ6s9SGxCH5o5i0oGBFbdCg0pE55Ao3acvLLuWistSDj0vkcPrQTg1bkg2l7RRG/4FSEKxRBUgEakepfTVco4pdIzK2/UaS2SNdj2c9S1oSk8gI6/N0luAz0Bq8iTgASCY4Xslqu6suCcjtxi7aIIkdSSB+hg23cvwqzWfpvT7PlyOb1ly6/oarTh5i8NOzcXSXHPnpymPOeZA9OLC7k+Op8OGnYDqBWWOY+rXwminKG2A8nTmyEZaL5ur/yn2HtUlEOHn59lP12NtRaz3e85Ap9g/aBxqdtzbwC7dQOT1NjpUJMTeJQKJwuiNKluEmWNhuJy1sbH+uj1bB4pqx6IsWTJr6vXblZGyZXfJbPYSCA1tIewaOwkCpYpgATcoySKgTKyi27cHGM5m6+bHQuFyFsS5Z5eGfWKfOBuzvj778p3iIZ1Fq/LrX+c/4v3+oIftmaUjkAmf6oyPAYQ4S5cmBRs+OCs+3+TkBgIyENPmTH+Tgh7/dRrT29yoad/uTJaY8hVEBdZJJS8QhIb60Ny7Q5Pbp77mhut7THwvoqrjN7ZuypsXQDQ60Bslhxnt2t7ezGEBKjpBL+NSyIevNlfQfG0JTOPSd2qCHmbkNvcg/xlyP9FoU7qvlhAA73knZr2RpAjckwCxcEkGyDFSo8a1e6MhGDGOFaXXypKMAo4s32JXKmvK51
  template:
    metadata:
      creationTimestamp: null
      name: nzbget-helm-values
      namespace: default
status: {}

