apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAvLIzlrk7ggecuYXLSI5/mO9w7eAaPJnNlH0L3AI8aR4AVYoVfOv7SMNfZfNB9AJ+pKF4PJ/oOIEHYYco9wHgdI9/y66mORU+wTNrkx2f3YqAdmsrd/Ijj8KuOqFIPDpf9hNyEnBm91hxZDzkZhGtN2qk29FKEAINmlp9qpEidhngdjLn2N9UNhLIuViEnARmd4mOZV69TkW01J2LGVuLbqBiBYvEJJQQ863x19diTmYN9e+bwcgwL1smxv2v50NXy3Y76UlmEVRXUtyX3B6Fl8VXa67xcEpJYJbyEWJseNG4+Kd3T0DUlIMB5ddptWL3P+ptAMpUKrmy4cRrys1b42o4MJVwfjDSjOidHLzcJJPKblAAq+3ksngDBcqnJSq8Ve4hjthecOGU3yEDo5Yu/9Ww2q8UOt8uDvUuJWvrE9TGQPWK0O0oTWsmQoNWvycJo8vGnA2pIL6mARYfabMgd6Eo6KVnZkcN4lGin54G2FtHJHLh5xXvS5sXCDkTz2y7CfXcFRIgfCtXM24UfADOBRr9wwOhDfPedBgEkLICtry6ofUKzGREDjtIYWybMwKdFkWX0BHZNbd+zsIJYFMOa2TsE126mGldSVc1m52JtO/CGZWUML3H6qySSs6iMK+wMjLBlmymsa+apSVJhSqw9RpbmsANo8b5nFhE6q+gNzU/Buyh97I504WAyecIlvNlpmay8dQpm2cKPgYVxpfGYzSQwz8aYYPpENvGcIRjsuwK96pisMVDCO2KrloeDcFRrHgpansPbzOrbhQIMW8PBCneyLTLtCXBPNUfXVlhD5TV3a6eRWrY4
  template:
    metadata:
      creationTimestamp: null
      name: nzbget-helm-values
      namespace: default
status: {}

