apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgC0aSI+UQpUlUORKPKb2w9ZummtNmzXFANma490zrT65fyXbQphIH8skDiKuAepih88OBQrkVq3fS8uCDi49VOTUZFpXnKOLhZ28CohlOY8vWRdBtal3VeSVOrDAtLvRPb4mWqAVRXlII+rY0v+bZm8MM/hO7QT5eQMcr4OjE9b4khRMp26DaPC7Q0FhEpL31TKMJwq4T2sa5IEilAsaS8BDqJJbTEZh6Yk7c8LnyLLF+Izn7oz27LR8xNWctTYzCvp9EbawKvG40lo5l1Ly0nYJ2fPI39aNfCzOz5WZY1XUFIaoRa+ZfFn3CqWHBgA2iXT9WajqCdNDhewxWUriwnpgNTEM+diR+qxPlgNUVOJYW9fpKk/muQK/zUPu/4+LDFrpGOVFdpadIUTyTlEsnLKzNKVFOwqpL/LYvf99Q0Pl+QJwkevGue7K0xXPns2QgwmUp7ZYlWx9/G+WWcIkFtdlwUUdirHzGgZbwPwFBtt8QzZGQYjtmuzEm3cStxg6kY6lQJLefqCLT59HUpfk0JyzMLODcL594rgB0U+Ebar1HniNGNC718uLapjtDwFdV6fsoM55HiExDP9pU3spE0vS+R/3scaBhaP+KFRxaE4BVZH5/uVHLJskF6garljqWIMbLKt3avKlB3YkTrIUhEYQFv5EM5JyjO9F2LSUxkgRRyeAKjw2cYft8OpehWyglOacxPSn27K0fFLM42YKlKkogks/AdEmWKxZs9KIWYctzDRX1fuwjJjmUZvvxIBQL9IojM0rhNvz0MbvadZYyJhVZKhrjQ+h3ucp1w/tzQrH89p0s9BUX20
  template:
    metadata:
      creationTimestamp: null
      name: nzbget-helm-values
      namespace: default
status: {}

