---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(v[0-9]+\.[0-9]+-ls.*)$'
spec:
  releaseName: nzbget
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts
    name: nzbget
    version: 4.0.1
  values:
    image:
      repository: linuxserver/nzbget
      tag: v21.0-ls69
    service:
      type: LoadBalancer
      loadBalancerIP: 10.100.100.230
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    persistence:
      downloads:
        enabled: true
        existingClaim: nfs-synology-pvc
        subPath: nzbget/downloads
      config:
        enabled: true
        storageClass: rook-ceph-block
        size: 1Gi
    puid: 1000
    pgid: 1000
    # podAnnotations:
    #   backup.velero.io/backup-volumes: config
    deploymentAnnotations:
      stash.appscode.com/backup-blueprint: default-workload-blueprint
      stash.appscode.com/target-paths: "/config"
      stash.appscode.com/volume-mounts: "config:/config"
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 400Mi
  valueFileSecrets:
  - name: "nzbget-helm-values"
