---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts
    name: plex
    version: 2.0.0
  values:
    image:
      repository: plexinc/pms-docker
      tag: plexpass
    timezone: "America/New_York"
    allowedNetworks:
      - 10.42.0.0/16
    advertiseIp: "http://10.100.100.220:32400"
    serviceTCP:
      type: NodePort
      externalIPs:
        - 10.100.100.220
      externalTrafficPolicy: Local
    serviceUDP:
      type: NodePort
      externalIPs:
        - 10.45.100.220
      externalTrafficPolicy: Local
    persistence:
      transcode:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 30Gi
      data:
        enabled: true
        claimName: nfs-synology-pvc
      config:
        storageClass: longhorn
        size: 300Gi
        accessMode: "ReadWriteOnce"
    # nodeSelector:
    #   app: "nvidia-gpu-plugin"
    resources:
      limits:
        # gpu.intel.com/i915: 1
        # nvidia.com/gpu: 1
        memory: 5009Mi
        cpu: 763m
      requests:
        cpu: 763m
        memory: 5009Mi