apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ombi-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCH41T0zsw7XQXKtcOzkSK2Hhg4jY6/b2+jbJzWHySuTYAzXsxcpGqyM1ckoRbgB+nqev94lHyvbyWjNyTF68iCx1QgMFe2cOGgiDdJJjHl2mVmHUWyHTn6ySBRUDB5lLXAtOpcPSESqCWed1raXnXvuQ97V5ZLOsUf1zE7pO90SoaU35rCy1mAXm958sWrYokhAuPrzLhINqB+oj6BSufzcCvYAo7WdroCJNJIcxsX6KUOYGPMyb1jmM+YxschQ+8TGqY/d82JA2Bqj93Co+Za/9F81vJgrQlINgWJE36v82n8HewZLPmcrDvuYeDLc34nnNh63V6w52NOo6lmjk/7DkRcMdWEPSt2CcD3lyKp+4Ojt+6n/jbuWs6c5gwYZ5ihYrYSltI/2aUC2dS0mvRpYcjsNz7KrJYYxEE70bAeiriET3i5ehPEHJklL3lXEBqUDswzZaoKs7isusIV8hS2ckH442lIEOfy5TtUYqPZTp1nVdRLuYXiMa609tk1fvGbnUqtWRDGEctN1h3od4c7vwnxN7XbqaFAkjWt/As07ea5ynY51uleWtUq781PSkfdNXRd1R5Ql6I3bno9D7G/cFrC1V5b/bINap1YfSKn6qWO8oeV0oA+JiTDwiVLuyKVCqjAZDBtHee0ZyHNml3KaQGqdjWWUVdWNX1Ft8DKmZIX9LhxpJHWcuS5qaePNq5fcyKQ4CfY/BbJflplT7VEvb+YpTR6JmYiOPxlkx+jvZINrQKLJTt1SYQI6GWbDFCNn0rNE/PWAZDLmNF7hN+ED9FSfvj7vHtzXZATMpbJ5F23XtNRTYA5
  template:
    metadata:
      creationTimestamp: null
      name: ombi-helm-values
      namespace: default
status: {}
