---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ombi
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: ombi
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: ombi
    version: 2.1.1
  values:
    image:
      repository: linuxserver/ombi
      tag: 3.0.5083-ls6
    deploymentAnnotations:
      stash.appscode.com/backup-blueprint: default-workload-blueprint
      stash.appscode.com/target-paths: "/config"
      stash.appscode.com/volume-mounts: "config:/config"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: 200Mi
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valueFileSecrets:
  - name: "ombi-helm-values"
