apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ombi-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCGjf6TxuKF4kFiEAFBJq1X9y+0LcmkYJE1KovVkX9l6No00hLthAKRrX0HZtV+4TBFFykD3QAzhPMWFonk4cRv8rukPJ/uSDUeHUNunFzkqvi5aDag+YhQOv6yTJ/JWA1ejl0o3f8hvVnqGIWFLjG3YolrJBBt8RRUyA/wSjsw6+yX2/rWoXqNpk9AcLnkDYuu/6o7kwuoWxcTCXaeg5VFInaC4bkqWur5lCgK5ODaHS6gNRXsMWU+YDftu7vp4FIv+eejVB/CgRb0fmXCW99SZRyUkSFAMN86aKLoO88DGKu1pvheJbnp5lxmtdMrKRG6ZLYYVFAunRqD6nCpIzOdOculBFnObuCpAJU1AFo9r0QC9JcwsNGielqY13YYcZfXGvUiYBq5Yl0ofIQ6MmyqW0GKsnklYur7EUPZ2oYdwrc+gXNuv2u5Ril6gW15QhCi/DuRBC7K7/kERo3PS6/CnoEHxOHOJSLayUpivwG37LKweS8Rz9Y0Lb3Dkh383op/TV4cc71t7iA3tIpc7TP2tfpqwuqbBv6B9bhatPkymuWvXQXh7CmfV0Qwhe7nGrqYmOPDUbwJK92JqzB6V3Ql4PUcjzjiah2Fo8Af6as37tvmVuB/WV/adfBvYNcbwVJFKi+5BDo0y2yd4lKupqMxJAb2o4lhrvYTPA4e31uecICWXVA7dtaCmC9OX6feCjwpKPEAwBK4iOSYunY0tQlTqOiFLcmJnqCYLEs5tTgqfcA87JtKY3f4SkR13k9NksQC9N/yqXINBbxhAqaOqhlX1/VmT6X+u2PrQ8SC0KI2vVTY0waHuCbGpoOfTA==
  template:
    metadata:
      creationTimestamp: null
      name: ombi-helm-values
      namespace: default
status: {}

