---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
  annotations:
    release: "tautulli"
    #fluxcd.io/automated: "true"
    #fluxcd.io/tag.chart-image: "glob:latest"
spec:
  releaseName: tautulli
  chart:
    repository: https://billimek.com/billimek-charts/
    name: tautulli
    version: 2.1.0
  values:
    image:
      repository: linuxserver/tautulli
      tag: v2.1.44-ls34
    deploymentAnnotations:
      stash.appscode.com/backup-blueprint: default-workload-blueprint
      stash.appscode.com/target-paths: "/config"
      stash.appscode.com/volume-mounts: "config:/config"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        storageClass: rook-ceph-block
        size: 5Gi
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valueFileSecrets:
    - name: "tautulli-helm-values"
