---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
  annotations:
    release: "tautulli"
    #fluxcd.io/automated: "true"
    #fluxcd.io/tag.chart-image: "glob:latest"
    #test
spec:
  releaseName: tautulli
  chart:
    repository: https://k8s-at-home.com/charts
    name: tautulli
    version: 3.0.1
  values:
    image:
      repository: linuxserver/tautulli
      tag: v2.5.4-ls11
      ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        storageClass: rook-ceph-block
        size: 5Gi
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valueFileSecrets:
    - name: "tautulli-helm-values"
