---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-synology-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: nfs-synology-pvc
  storageClassName: nfs-client
  nfs:
    server: 10.100.100.11
    path: "/volume1/videos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-synology-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Mi