master:
  hosts:
    k8s-mgmt:
      ansible_host: k8s-mgmt.nemisphere.com
  vars:
    k3s_control_node: true
    k3s_tls_san: "k8s.nemisphere.com"

nodes:
  hosts:
    k8s-01:
      ansible_host: k8s-01.nemisphere.com
    k8s-02:
      ansible_host: k8s-02.nemisphere.com
    k8s-03:
      ansible_host: k8s-03.nemisphere.com
  vars:

ceph:
  hosts:
    k8s-01:
      ansible_host: k8s-01.nemisphere.com
    k8s-02:
      ansible_host: k8s-02.nemisphere.com
    k8s-03:
      ansible_host: k8s-03.nemisphere.com
  vars:

nfs:
  hosts:

  vars:

arm:
  hosts:

  vars:

k3s_cluster:
  children:
    master:
    nodes:

storage:
  children:
    ceph:
    nfs:

vault:
  hosts:
    localhost:
      ansible_connection: local