---

- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - { role: prepare_nodes }
    - { role: xanmanning.k3s }

- hosts: master
  gather_facts: true
  become: true
  roles:
    - { role: kubeconfig }

- hosts: localhost
  gather_facts: false
  become: false
  roles:
    - { role: k3s/bootstrap }
    - { role: flux }
    - { role: helm_operator, when: helm_operator == true }
