---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+)$'
spec:
  releaseName: influxdb
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: influxdb
    version: 3.0.2
  values:
    image:
      repository: "influxdb"
      tag: "1.8.4"
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      size: 50Gi
      storageClass: rook-ceph-block
    resources:
      requests:
        memory: 2000Mi
        cpu: 100m
      limits:
        memory: 3000Mi
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    config:
      opentsdb:
        enabled: true
